### ISSUE TITLE
License concerns

### ISSUE THREAD

**Issue by uqsme** [soralis0912/TwiFucker2#2]
3月2日补注，后来的就收收嘴吧，别无脑冲这个日本开发者了，他是无心之失。 真正的Nullptr最终[也同意了](https://t.me/TwiFuckerDiscussion/32428)。

分割线下为原文  

-----
(I don't speak Japanese.)

Hello, I just heard that you restarted "open source" TwiFucker and that's great, wish you success. But I'm concerned about how  you develop this. It seems that [you copied original TwiFucker's code](https://github.com/soralis0912/TwiFucker2/commit/692512fc4177b597486362a1729e2b56b0bdb65d) and attempted to modify the source, literally **based on** the original project.
I'm kinda worried because the original authors has stated that `ALL RIGHTS RESERVED` [regarding to the original code](https://github.com/Dr-TSNG/TwiFucker?tab=readme-ov-file#%EF%B8%8F-copyright-notice), and actually they never applied an open source license despite being source-accessible. So it's basically illegal for anyone to recreate a software just rely on original TwiFucker.

I wonder if you have ever noticed the restriction, or have you negotiated with original authors and got a special license to use their code?

**Comment by monefiera** [comment]
Hello. We  didn't notice of those problems.
Thanks for making us aware.
However, Dr-TSNG/Nullptr has not taken any action against all the projects he seems to have appropriated the source code ([despite knowing about Revanced](https://t.me/TwiFuckerDiscussion/20622)). The same can be said for iKirby and therealswak mods, which we believe are at least in a state of 'illegal but he won't sue'. As long as it is clearly credited, I think it is even less likely.
Nevertheless, since we call this project Twifucker2, so I believe that it would be more than illegal and dishonest to proceed without informing him. I intend to contact him once.
We'll also do my utmost to ensure that [no project will appear that could be abused](https://aerowitter.com/) due to a lack of licensing.

**Comment by CoolCooler0** [comment]
As long as the original Twifucker creators get credit I think this will be fine. All the best with this.

**Comment by uqsme** [comment]
> As long as the original Twifucker creators get credit I think this will be fine. All the best with this.

Maybe it isn't that simple. Faker.js's author got credited but he stilled chose to [discontinue the project](https://www.reddit.com/r/programming/comments/rz5rul/marak_creator_of_fakerjs_who_recently_deleted_the/).

<!-- you can't see this :laughing: >

**Comment by monefiera** [comment]
> Maybe it isn't that simple. Faker.js's author got credited but he stilled chose to [discontinue the project](https://www.reddit.com/r/programming/comments/rz5rul/marak_creator_of_fakerjs_who_recently_deleted_the/).

Hmm…
But in this case, it remains to be seen what will happen since the objective is to revive a project that has **already cancelled**. Hopefully he won't tell us to freeze the development...
I've already sent a message to Dr-TSNG, so I'm just waiting for his answer.

**Comment by monefiera** [comment]
~~He graciously replied that it was no problem.~~
~~It's really helpful news!~~
Apparently I was deceived (I disclose the screenshot because I don't have to hide it).
![IMG_20240301_145715_671](https://github.com/soralis0912/TwiFucker2/assets/83483662/a074d393-5bfc-4818-81dd-45380c3488ab)

**Comment by uqsme** [comment]
> He graciously replied that it was no problem. It's really helpful news!

Cheers!

**Comment by Dr-TSNG** [comment]
> He graciously replied that it was no problem. It's really helpful news!

~I had **NEVER** granted **ANY** permission nor had **ANYONE** messeged me. What the fuck are you talking?~

Edited: Seems that someone used a fake Telegram pretending to be me.

**Comment by Ssj1234567899** [comment]
Thanks

**Comment by monefiera** [comment]
This is my fault for not carefully checking my contacts so I apologize.
Edit on 2024/3/5：I've prepared [the detailed report on my failure](https://note.com/forsaken_love02/n/nab791d3bd856) in chronological order (written in Japanese, use Translator if you can't read).
As Mr.LatticeLadder notes in his postscript, **we settled with Dr-TSNG early on**. I will not accept all bashing against anyone other than my fault (i.e., Soralis and other developers).

**Comment by akashi04s** [comment]
ew these devs are such crybabies crying after credits and abuses. fucking snowflakes. just discontinue everything for fucks sake. every month one of these retards start crying for credit and shit lol

**Comment by TheInterestingS0ul** [comment]
I (SkymontVibe) am a stupid fool who likes to shit on other people's head but then I realized I'm the shittiest one of them all. 😋
Check my homepage to see what I've done.
https://github.com/RewindBird
